name: erddapdemo
channels:
  - conda-forge
dependencies:
    - jupyterlab
    - matplotlib
    - xarray
    - cartopy
    - cmocean
    - jupyterlab_widgets
    - ipywidgets
    - tqdm
    - erddapy<2.0.0
